### ISSUE TITLE
似乎因为作者改了GitHub用户名，导致jsdelivr同步的字体引用失效

### ISSUE THREAD

**Issue by mingchau** [lovezsh/v2ex_theme#4]
https://cdn.jsdelivr.net/gh/anghunk/cdn/font/HarmonyOS_Sans_SC_Medium.woff2

**Comment by anghunk** [comment]
> https://cdn.jsdelivr.net/gh/anghunk/cdn/font/HarmonyOS_Sans_SC_Medium.woff2

是的，这个我忘记修改了😁直接把用户名改一下就行了

**Comment by mingchau** [comment]
> > https://cdn.jsdelivr.net/gh/anghunk/cdn/font/HarmonyOS_Sans_SC_Medium.woff2
> 
> 是的，这个我忘记修改了😁直接把用户名改一下就行了

就是v2ex_theme.min.css这里的第一行代码要改啊 🤣

**Comment by anghunk** [comment]
> > > https://cdn.jsdelivr.net/gh/anghunk/cdn/font/HarmonyOS_Sans_SC_Medium.woff2
> > 
> > 
> > 是的，这个我忘记修改了😁直接把用户名改一下就进行了
> 
> 就是v2ex_theme.min.css这里的第一行代码要改啊🤗

多谢提醒，已经修好了文件
